### ISSUE TITLE
Printing help for subcommands could also print subcommand doc

### ISSUE THREAD

**Issue by mjdorma** [aliles/begins#11]
Taking the following example:

``` python
@begin.subcommand
def world(woot):
    "The world w00t doc goes here"

@begin.start
def main():
    "The main doc goes here"
    pass
```

Help on the main program yields the doc string being printed in the following:

``` bash
 > python test.py -h
usage: test.py [-h] {world} ...

The main doc goes here

optional arguments:
  -h, --help  show this help message and exit

Available subcommands:
  {world}
    world     The world w00t doc goes here
```

Help on the subcommand world yields the following:

``` bash
 python test.py world -h
usage: test.py world [-h] -w WOOT

optional arguments:
  -h, --help            show this help message and exit
  -w WOOT, --woot WOOT
```

Would it be reasonable to print "The world w00t doc goes here" between the usage statement and the optional arguments block?

**Comment by aliles** [comment]
Yes, this is actually a bug. The intention was for the docstring of sub-command functions to appear in the help output as the sub-command description.
