### ISSUE TITLE
Explore the option of implicit type conversion

### ISSUE THREAD

**Issue by mjdorma** [aliles/begins#12]
After talking with Aaron on chat regarding input argument types, I touched on the idea of implicitly converting input parameter values to the type found in the default value assigned to a kwarg.

There are pros and cons (and dragons) in this idea.  Especially if this were to be applied to any type.  Aaron raised the question of how would this work for types such as files?  

Currently the @begin.cast decorator allows you to implement explicit conversions for individual kwargs (this is especially useful for more complicated types such as file). 

Maybe we could start off by implicitly converting a very limited (or even one) set of types.  
- int: Should be simple to implicitly convert. 
- bool: May fit into a different category of solution as discussed in issue #10.
- str: Is the default type from ArgParse.  

Maybe the title of this issue should be labelled _"Implicitly converting kwargs with a default int assignment"_

**Comment by aliles** [comment]
I'm very concerned that implicit type conversion that isn't request by the developer would violate the [Principle of Least Astonishment](http://lucumr.pocoo.org/2011/7/9/python-and-pola/). What about a solution where the developer was able to explicitly request 'magic' from `begin.convert()`? For example:

``` python
@begin.start
@begin.convert(_magic=True)
def main(host='127.0.0.1', port=8080, debug=True):
    pass
```

Would result in the equivalent call to `begin.convert()` as:

``` python
@begin.convert(port=int, debug=begin.util.tobool)
```

Also, should the number of support functions in the `begin.util` module should be increased either before or in conjunction with adding implicit type conversion. (Handling files and tuples/sequences) Or should the initial version be limited to `int`, `float` and `bool`?
