### ISSUE TITLE
Program name miss labelled when __main__ is a package in __main__.py

### ISSUE THREAD

**Issue by mjdorma** [aliles/begins#15]
This bug was pointed out to me today by Aaron :+1:   

Taking the following program modfoo:

``` bash
$ find modfoo
modfoo
modfoo/__main__.py
modfoo/__init__.py
```

Where **main**.py is:

``` python
import begin

@begin.start
def main(bar="moo"):
    print(bar)
```

I get the following output:

``` bash
$ python -m modfoo -h
usage: __main__.py [-h] [--bar BAR]

optional arguments:
  -h, --help         show this help message and exit
  --bar BAR, -b BAR  (default: moo)
```

Instead of **main**.py I would have expected modfoo.

**Comment by aliles** [comment]
I remember pointing this out, but I'm unable to reproduce from the description above. Was the example `modfoo` installed as a [console script](http://peak.telecommunity.com/DevCenter/setuptools#automatic-script-creation) using setuptools or distribute?

**Comment by aliles** [comment]
Ok. I was just being silly. This issue can be reproduced by:

``` bash
$ python modfoo/__main__.py
```

Which is equivalent to what setuptools does when running `modfoo/__main__:main` as a console script.

**Comment by mjdorma** [comment]
Good to hear.  Sorry that I didn't get back to you sooner on this one ...  Slacker move on my part!

Cheers
