### ISSUE TITLE
Feature Request: Run multiple sub commands

### ISSUE THREAD

**Issue by JoeyJoJoJrShabadu** [aliles/begins#16]
It would be handy to have the ability to be able to run multiple sub commands at once.

An example use case is some sort of insertion script that has variable arguments depending on which input system and which output system is chosen.  An example of this might be 'insert.py [INPUT SYSTEM] --in_arg1 --in_arg2 [OUTPUT SYSTEM] --out_arg1 --out_arg2' where the list of arguments required will differ per system.

**Comment by mjdorma** [comment]
Would this imply you would want to execute each entry in the order defined:
1. input_system
2. output_system
3. main

Thus allowing for "things" to happen in 1 and 2 then finally execute main? 

Something like:

``` python
import begin

input = None
output = None

@begin.subcommand
def iweb(url):
    "A url reader" 
    import urllib
    input = urllib.urlopen(url)

@begin.subcommand
def ifile(filepath):
    "A filepath reader"
    input = open(filepath, 'rb')

@begin.subcommand
def ofile(filepath):
    "A filepath to output in to"
    output = open(filepath, 'wb')

@begin.start
def main():
    "read write stream demo"
    assert input is not None and output is not None
    input.write(output.read())
```

Which means I could:

``` bash
 $ demo.py iweb --url https://github.com/aliles/begins/issues/16 ofile --filepath test.txt
```

**Comment by aliles** [comment]
My proposed solution for this is to have `begin.start()` accept a command delimiter that marks the boundaries between commands. For example:

``` python
@begin.start(cmd_delim="--")
def main():
    pass
```

This application would now allow multiple commands to be separated using `--`.

My current thinking is to not to have begins deal with dependencies between subcommands. I am (strongly) considering adding a context global to the `begin` module that would be available to all subcommands. This could store details of previous, current and next commands. The return value from any previous command. As well as serve as a global namespace for commands to store objects.

The context global's original motivation was to allow bootstrapping (such as creating network connections to databases, web servers etc) in the main function which are generic to all the subcommands. I see chaining of subcommands as a generalisation of the current pattern of calling the main function and a subsequent subcommand.
