### ISSUE TITLE
Curly bracketed sub commands in help output

### ISSUE THREAD

**Issue by mjdorma** [aliles/begins#20]
Is there a way to suppress the second print out of the sub commands between the curly brackets?  

For example, can we take the following program:

```
python test.py -h
usage: test.py [-h] {bar,foo,moo} ...

this is the main program

optional arguments:
  -h, --help     show this help message and exit

Available subcommands:
  {bar,foo,moo}
    bar          this is the bar command
    foo          this is the foo command
    moo          this is the moo command
```

And make it:

```
python test.py -h
usage: test.py [-h] {bar,foo,moo} ...

this is the main program

optional arguments:
  -h, --help     show this help message and exit

Available subcommands:
    bar          this is the bar command
    foo          this is the foo command
    moo          this is the moo command
```

As an extension to this activity, could we suppress both print outs to yield something like:

```
python test.py -h
usage: test.py [-h] COMMAND ...

this is the main program

optional arguments:
  -h, --help     show this help message and exit

Available subcommands:
    bar          this is the bar command
    foo          this is the foo command
    moo          this is the moo command
```

In the cases where a program has many sub commands this list is not useful and adds additional text for users to decipher.

**Comment by aliles** [comment]
I agree that removing (at least) the second short list of available subcommands as it's redundant above the complete descriptions immediately below. Less sure about the command list in the usage line if it doesn't make the line too long.

The help message is generated automatically by argparse's default help formatter. If I can figure out how to sublcass the default formatter and provide it back to the ArgumentParser I will implement this in at least part. If not all.

**Comment by mjdorma** [comment]
Solution provided in final comment #32
