### ISSUE TITLE
RST formatted __doc__ for help

### ISSUE THREAD

**Issue by mjdorma** [aliles/begins#23]
A few weeks ago I was demonstrating some of the fu behind begins to a work colleague and he raised an interesting questioned about format of the `**doc** strings when printing out help. 

As a feature request, would it be possible to strip [RST](http://docutils.sourceforge.net/rst.html) formatted text and let it printout in a neat plaintext format?

**Comment by mjdorma** [comment]
Adding to this - even just a plain text printout would be an improvement. No need for RST fu.

**Comment by aliles** [comment]
I'm quite positive about this idea, I've seen people using reStructuredText formatter docstrings for great value. The challenge here is that [docutils](http://docutils.sourceforge.net/) doesn't acutally provide a [plain text publisher](http://docutils.sourceforge.net/docs/api/publisher.html) for reStructuredText.

Hopefully I'll find an additional reason to work on docutils which will enable further progress on this issue.

**Comment by aliles** [comment]
Fixed in commit 8bb7c43326a9a355ffb8730cfce5c428ff5ddc45
