### ISSUE TITLE
Main called for each subcommand 

### ISSUE THREAD

**Issue by mjdorma** [aliles/begins#33]
When stringinng together multiple subcommands, main gets invoked per command.

Taking the following program:

```
> cat test.py
import begin
import argparse

@begin.subcommand
def foo():
    pass

@begin.subcommand
def bar():
    pass

@begin.start(cmd_delim='--')
def main():
    print("Called")
    pass
```

We get the following output to show that main is "Called" for foo and bar.

```
python test.py bar -- foo
Called
Called
```

**Comment by mjdorma** [comment]
Discussing the idea of when main should be called.  It becomes apparent very quickly that the most logical and most convenient time for it to be called is first.  

First and foremost, "main" is the _start_ of the program.  Anything less would be confusing.  Second, this is the one logical place where a program can initialise its internal state (database connections etc.).  

Finally, understanding main in the way just described demonstrates how multiple calls to main is undesirable behavior.

**Comment by aliles** [comment]
Yes, and `begin.context` can be used to store state that should be accessible by subcommands, such as database connections. :smile:
