### ISSUE TITLE
A concise approach to flags 

### ISSUE THREAD

**Issue by mjdorma** [aliles/begins#35]
Last week my colleague pointed out to me that using flags in begins was awkward and not intuitive. He then showed me a neat approach other popular command line interfaces adopt in the wild for setting a flag true vs flag false.  

Taking the following code:

```
import begin

@begin.start
def main(flag=False):
    print("flag = %s" % flag)
```

The following output can be achieved:

```
usage: foo.py [-h] [--flag]

optional arguments:
  -h, --help  show this help message and exit
  --flag      enable flag
```

Now, changing the default value of flag=True:

```
import begin

@begin.start
def main(flag=True):
    print("flag = %s" % flag)
```

We could get:

```
usage: foo.py [-h] [--no-flag]

optional arguments:
  -h, --help  show this help message and exit
  --no-flag   disable flag
```

From a programmer point of view we only have one variable 'flag' and no need for inventing a word that matches the negation of its default state.  And for the user of the "cli" we now have an intuitive natural language way for setting the state of flag to on or off.

**Comment by aliles** [comment]
Agreed, the interpretation of an argument's name vs it's default value vs the interpretation on the command line can be quit torturous with the current behavior. The inversions involved can get very tedious.

What about short options though? (This has implications for #36) I think short args should continue to be supported for the long argument after --no. For example --no-fork and -f.

The short arg continues to suffer the same issues described above. However, it's tied to the more explicit long option, including on the cli help output. I expect this would mitigate the issues while not penalizing users that become familiar with a tools cli.

**Comment by mjdorma** [comment]
There is an issue in this behavior. From ArgParse we can pragmatically change the state of the help by removing one option and inserting the correct text depending on the variables "default" state. 

In the case that we change the default state in the configuration file, or in a global environment variable, we end up with a cli which potentially accepts a different set of input arguments.  It is common practice to build shell scripts which hardcode various input parameters.  Say we created a shell script that sets or unsets flag values (--[flag] vs --no-[flag]) we would expect the cli to be able to handle both types of input independent of the flag's default state.  

To mitigate this issue, I propose from the "interface" we could accept the incoming negated variable state and ignore it if the opposite default holds true. 

From the first example on the previous post we could:

```
> python foo.py -h
usage: foo.py [-h] [--flag]

optional arguments:
  -h, --help  show this help message and exit
  --flag   enable flag

> python foo.py --no-flag
flag = False
```

From the last example on the previous post we could:

```
> python foo.py -h
usage: foo.py [-h] [--no-flag]

optional arguments:
  -h, --help  show this help message and exit
  --no-flag   disable flag

> python foo.py --flag
flag = True
```

**Comment by mjdorma** [comment]
Thinking through the short arg for flag issue...  There lies a risk of serious confusion when the default value changes due it being inverted in the environment or configuration state.  What will a short arg do to the state of flag argument?  

If it were to invert the default state of the parameter because the short flag had be passed through the cli we will result in awkward and ambiguous behavior (which is what this issue is trying to resolve).

I'd be keen to hear (spitball) alternative strategies in which we could process the short argument.

**Comment by aliles** [comment]
To summarise the state of discussion:
- Accept both of  `--opt` and `--no-opt` for boolean flag options on the command line.
- Do not support short args with boolean flag options. Only long options.

Hopefully the last question: is it reasonable to suppress the 'noop' version of the argument flag from the help output? It would still be accepted, just not displayed.

**Comment by mjdorma** [comment]
Question could be, what is the cost of supporting one vs the other or even both? 

Option one, print !default with some doc that says "turn opt on" or "turn opt off". Could seem less confusing, but may be odd when a user sees a flag being passed in where the help doesn't mention it.

Option two, print both and mark the default. This is more explicit but adds additional detail to the help which may increase the complexity for a user when they are attempting to decipher the help. 

To me it's a detail that could be decided based on the complexity of the code. I'm clearly for and against it at the same time ;).

**Comment by aliles** [comment]
Another alternative. Always display both `--opt` and `--no-opt` but only dispaly the `(default: ...)` information for the active flag. A worked example is documented [in this gist](https://gist.github.com/aliles/9069387).

**Comment by mjdorma** [comment]
:+1:
