### ISSUE TITLE
Translate Pythonic argument name underscores to dashes

### ISSUE THREAD

**Issue by mjdorma** [aliles/begins#37]
I propose we translate underscores in argument names to dashes. 

This simple change makes the cli of begins feel less like Python and more a shell program whilst maintaining a good Python naming practice.  This idea was inspired by the complex and comprehensive interfaces of clang and gcc.

Taking the following program:

```
import begin

@begin.start
def main(my_param_one, my_param_two="foo"):
    pass
```

We could get this (note my-variable-two):

```
usage: test.py [-h] [--my-variable-two MY_VARIABLE_TWO] MY_VARIABLE_ONE

positional arguments:
  MY_VARIABLE_ONE

optional arguments:
  -h, --help            show this help message and exit
  --my-variable-two MY_VARIABLE_TWO, -m MY_VARIABLE_TWO
                        (default: foo)
```

**Comment by aliles** [comment]
This is quite a reasonable proposal. The cli does look prettier, and beautiful is better than ugly. What about environment variables and configuration files? Should these remain underscores? Would that be non-obvious?

**Comment by mjdorma** [comment]
To date I have always (almost always) seen globals caps underscore. This seems to be the common convention.

**Comment by aliles** [comment]
Final question, does this only apply to command line options, not required options? eg:

```
import begin
@begin.start
def main(req_opt, opt_opt='optional', *var_args):
    pass
```

Generating the command line

```
usage: translate.py [-h] [--opt-opt OPT_OPT] REQ_OPT [var_args [var_args ...]]

positional arguments:
  REQ_OPT
  var_args

optional arguments:
  -h, --help            show this help message and exit
  --opt-opt OPT_OPT, -o OPT_OPT
                        (default: optional)
```

Note the `--opt-opt` option rather the `--opt_opt`.

**Comment by mjdorma** [comment]
I'd say yes, only options :+1:. Typing - is one less push then _ which is what is at the heart of this issue.
