### ISSUE TITLE
kwargs starting with h in @begin.start

### ISSUE THREAD

**Issue by mjdorma** [aliles/begins#6]
kwargs starting with h will change the meaning of "-h" help to the kwarg defined in the function.

**Comment by aliles** [comment]
Begins uses argparse's default [conflict handler](http://docs.python.org/dev/library/argparse.html#conflict-handler) to handle conflicts over short (and long) option flags. My preference is for user defined options to always take precedence over the default options set by begins. However, I'm open to discussion.

(This is something that requires in depth documentation when the reference guide is written.)

**Comment by aliles** [comment]
Following conversation on chat, the current (intended) conflict resolution for options is to provide precedence to the most important user supplied option. In lieu of a better conflict resolution mechanism, can this issue be closed with a new section being pushed to the current docs describing how conflicts are resolved?

**Comment by mjdorma** [comment]
Sounds like a great resolution.  In any case, reserving -h for help is not absolutely true for all time.
