### ISSUE TITLE
Newlines in description

### ISSUE THREAD

**Issue by perlyking** [aliles/begins#66]
When the description that follows the **start** function definition has newlines, these are ignored when the user invokes the program with `-h`. It would be useful if these were retained to make the usage instructions more legible.

e.g.,

```
@begin.start
def main(option='foo'):
    """
    Here is the description

    For clarity it is split into paragraphs

    Here is another.
    """
    # code starts

$ ./script.py -h

usage: script.py [-h] [--option OPTION]

Here is the description For clarity it is split into paragraphs Here is
another.

optional arguments:
  -h, --help            show this help message and exit
  --option OPTION, -o OPTION
                        (default: foo)
```

**Comment by ctwardy** [comment]
I second this. Esp. handy for EXAMPLE lines to begin on new lines.
Right now, this:
```python
# -*- coding: utf-8 -*-
import begin

@begin.start
def main():
    """A multiline docstring:

    EXAMPLE: python multipass.py
    """
    pass
```
becomes:
```
usage: multipass.py [-h]

A multiline docstring: EXAMPLE: python multipass.py

optional arguments:
  -h, --help  show this help message and exit
'''

**Comment by mjdorma** [comment]
FYI: you can simply decorate your start with the formatter RawDescription.


class begin.formatters.RawDescription[source]
Help message formatter which retains any formatting in descriptions.
Based on argparse.RawDescriptionHelpFormatter from Python standard library.

**Comment by ctwardy** [comment]
Ah. Well never mind then. 🙂

Snt frm a mbl phn.

On Mar 16, 2017, at 4:01 PM, Michael Dorman <notifications@github.com> wrote:

FYI: you can simply decorate your start with the formatter RawDescription.

class begin.formatters.RawDescription[source]
Help message formatter which retains any formatting in descriptions.
Based on argparse.RawDescriptionHelpFormatter from Python standard library.

**Comment by perlyking** [comment]
Thanks! For reference, I did

`@begin.start(formatter_class=begin.formatters.compose(begin.formatters.RawDescription))`
