### ISSUE TITLE
To fix help comment.

### ISSUE THREAD

**Issue by sshkim** [aliles/begins#72]
Installed version 
`pip install begins==0.9`

The help command is wrong.

I command with space, it doesn't work. But I command with '=', it's okay.

Help command like below.

![image](https://user-images.githubusercontent.com/20734605/83484028-ef238980-a4de-11ea-9ce7-44031a23218e.png)

It doesn't work
`python begin.py -s 'storage'`

It works
`python begin.py -s='storage'`

I think it needs to fix this comment.

**Comment by harkabeeparolus** [comment]
> I think it needs to fix this comment.

Currently, this project seems to be abandoned, so please don't keep your hopes up for any fixes.

See this thread for alternatives to this project: https://github.com/aliles/begins/issues/64#issuecomment-578627136
